repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: (doc/ReleaseNotes.md)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.4'
    hooks:
      - id: clang-format