name: Run pre-commit and apply changes

on:
  issue_comment:
    types:
      - created

jobs:
  pre-commit-fix:
    # Only makes sense on PRs here and we also immediately filter out any other
    # comments than "/fix-style"
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/fix-style')
    runs-on:
      ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
      issues: write

    steps:
      - uses: actions/checkout@v3
      - name: Post confirmation comment
        id: cc
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Let me try to fix that for you
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr checkout ${{ github.event.issue.number }}
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - name: Run pre-commit
        run: |
          source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
          pip install pre-commit
          pre-commit run --all-files || status=$?
      - name: Commit and push changes
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[format] pre-commit autofix"
          status_options: "--untracked-files=no"
          add_options: "-u"
      - name: Update comment with no changes
        uses: peter-evans/create-or-update-comment@v3
        if: steps.auto-commit.outputs.changes_detected == 'false'
        with:
          comment-id: ${{ steps.cc.outputs.comment-id }}
          body: |
            **Edit:** No changes applied
      - name: Update comment with changes
        uses: peter-evans/create-or-update-comment@v3
        if: steps.auto-commit.outputs.changes_detected == 'true'
        with:
          comment-id: ${{ steps.cc.outputs.comment-id }}
          body: |
            **Edit:** Fixes applied
      - name: Report failure
        uses: peter-evans/create-or-update-comment@v3
        if: ${{ failure() }}
        with:
          comment-id: ${{ steps.cc.outputs.comment-id }}
          body: |
            **Edit:** Workflow failure
