name: pre-commit

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: centos7
        view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
        run: |
          git config --global --add safe.directory $(pwd)
          export PATH=/root/.local/bin:$PATH
          pip install pre-commit
          pre-commit run --show-diff-on-failure \
            --color=always \
            --all-files
